#!/bin/bash
# ================================================================
# INTELISHOP - GOOGLE OAUTH SETUP SCRIPT
# ================================================================
# Script này hướng dẫn bạn từng bước setup Google OAuth
# Chạy trên Windows PowerShell / Git Bash / Mac Terminal / Linux
# ================================================================

echo "================================================"
echo "🦋 INTELISHOP - GOOGLE OAUTH SETUP"
echo "================================================"
echo ""

# ========== STEP 1: Google Cloud Console ==========
echo "📋 BƯỚC 1: Tạo Google OAuth Credentials"
echo "================================================"
echo ""
echo "1. Truy cập: https://console.cloud.google.com/"
echo "2. Tạo PROJECT MỚI (nếu chưa có)"
echo "   - Click 'Select a Project' → 'NEW PROJECT'"
echo "   - Project name: Intelishop"
echo "   - Click CREATE"
echo ""
echo "3. Tạo OAUTH CONSENT SCREEN"
echo "   - Click 'Consent Screen' (trái sidebar)"
echo "   - Chọn 'External' → 'CREATE'"
echo "   - App name: Intelishop"
echo "   - User support email: [your-email]"
echo "   - Developer contact: [your-email]"
echo "   - Click SAVE AND CONTINUE → SAVE AND CONTINUE → BACK TO DASHBOARD"
echo ""
echo "4. Tạo OAUTH 2.0 CLIENT ID"
echo "   - Click 'Credentials' (trái sidebar)"
echo "   - Click 'CREATE CREDENTIALS' → 'OAuth 2.0 Client IDs'"
echo "   - Chọn 'Web application'"
echo "   - Name: Intelishop Web"
echo "   - Authorized JavaScript origins:"
echo "     * http://localhost:5500"
echo "     * http://127.0.0.1:5500"
echo "     * http://localhost:3000"
echo "   - Authorized redirect URIs:"
echo "     * http://localhost:8000/accounts/google/login/callback/"
echo "     * http://127.0.0.1:8000/accounts/google/login/callback/"
echo ""
echo "5. ⭐ COPY CLIENT ID & CLIENT SECRET"
echo "   (Bạn sẽ cần dùng nó trong bước 2)"
echo ""
read -p "Bấm ENTER khi đã hoàn tất... "

# ========== STEP 2: Cấu hình .env Backend ==========
echo ""
echo "📋 BƯỚC 2: Cấu hình Backend .env"
echo "================================================"
echo ""

# Kiểm tra file .env
if [ ! -f "intelishop_backend/.env" ]; then
    echo "⚠️  File .env không tồn tại!"
    echo "   Tạo file .env từ template..."
    cp intelishop_backend/.env.example intelishop_backend/.env
    echo "✅ File .env đã được tạo"
fi

echo ""
echo "1. Mở file: intelishop_backend/.env"
echo "2. Cập nhật các biến:"
echo ""
echo "   GOOGLE_OAUTH_CLIENT_ID=YOUR_CLIENT_ID_HERE"
echo "   GOOGLE_OAUTH_CLIENT_SECRET=YOUR_CLIENT_SECRET_HERE"
echo "   FRONTEND_URL=http://localhost:5500"
echo "   GEMINI_API_KEY=your-gemini-api-key"
echo ""
echo "3. Lưu file"
echo ""
read -p "Bấm ENTER khi đã cập nhật .env... "

# ========== STEP 3: Django Admin Setup ==========
echo ""
echo "📋 BƯỚC 3: Cấu hình Django Admin"
echo "================================================"
echo ""
echo "1. Chắc chắn Backend đang chạy:"
echo "   cd intelishop_backend"
echo "   python manage.py runserver"
echo ""
echo "2. Truy cập: http://127.0.0.1:8000/admin/"
echo "3. Login với superuser account"
echo ""
echo "4. Vào Django > SITES"
echo "   - Click vào 'example.com'"
echo "   - Domain name: localhost:8000"
echo "   - Display name: Intelishop"
echo "   - SAVE"
echo ""
echo "5. Vào SOCIAL APPLICATIONS"
echo "   - Click ADD SOCIAL APPLICATION"
echo "   - Provider: Google"
echo "   - Name: Google OAuth"
echo "   - Client id: [CLIENT ID từ Google Cloud]"
echo "   - Secret key: [CLIENT SECRET từ Google Cloud]"
echo "   - Sites: Chọn 'localhost:8000'"
echo "   - SAVE"
echo ""
read -p "Bấm ENTER khi đã hoàn tất... "

# ========== STEP 4: Cập nhật Frontend ==========
echo ""
echo "📋 BƯỚC 4: Cập nhật Frontend"
echo "================================================"
echo ""
echo "1. Mở file: intelishop_frontend/index.html"
echo ""
echo "2. Tìm dòng:"
echo "   YOUR_GOOGLE_CLIENT_ID_HERE"
echo ""
echo "3. Thay thế bằng Client ID từ Google Cloud:"
echo "   your-client-id-xxx.apps.googleusercontent.com"
echo ""
echo "4. Lưu file"
echo ""
read -p "Bấm ENTER khi đã cập nhật... "

# ========== STEP 5: Test ==========
echo ""
echo "📋 BƯỚC 5: Kiểm tra hoạt động"
echo "================================================"
echo ""
echo "✅ Hãy làm theo các bước sau để test:"
echo ""
echo "1. Chắc chắn Backend đang chạy:"
echo "   cd intelishop_backend"
echo "   python manage.py runserver"
echo ""
echo "2. Mở Frontend:"
echo "   - Nếu dùng VS Code Live Server:"
echo "     Click 'Go Live' hoặc vào http://localhost:5500"
echo "   - Hoặc chạy local server khác"
echo ""
echo "3. Click 'Đăng Nhập' trên Intelishop"
echo ""
echo "4. Bạn sẽ thấy button Google"
echo ""
echo "5. Click Google button:"
echo "   - Chọn Gmail account"
echo "   - Xác nhận permissions"
echo "   - Bạn sẽ được đăng nhập"
echo ""
echo "6. Kiểm tra Django Admin:"
echo "   - Vào http://127.0.0.1:8000/admin/Users"
echo "   - User mới từ Google sẽ xuất hiện"
echo ""

# ========== TROUBLESHOOTING ==========
echo ""
echo "🐛 TROUBLESHOOTING"
echo "================================================"
echo ""
echo "❌ 'Lỗi xử lý mạng xã hội' khi click Google:"
echo "   → Kiểm tra F12 console xem error gì"
echo "   → Kiểm tra Client ID trong index.html khớp với Google Cloud"
echo "   → Kiểm tra FRONTEND_URL trong .env"
echo ""
echo "❌ 'Callback URL không hợp lệ':"
echo "   → Vào Google Cloud Console"
echo "   → Credentials → OAuth 2.0 Client IDs"
echo "   → Cập nhật 'Authorized redirect URIs'"
echo ""
echo "❌ 'Sai Domain' khi truy cập Django Admin:"
echo "   → Vào Django Admin > SITES"
echo "   → Cập nhật Domain name thành 'localhost:8000'"
echo ""

echo ""
echo "================================================"
echo "✨ Thiết lập hoàn tất!"
echo "Bây giờ bạn có thể dùng Google để đăng nhập Intelishop"
echo "================================================"

