# Generated by Django 5.2.11 on 2026-03-01 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cửa hàng')),
                ('icon', models.CharField(max_length=10, verbose_name='Icon (Emoji)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá ($)')),
                ('image', models.CharField(max_length=10, verbose_name='Hình ảnh (Emoji)')),
                ('category', models.CharField(max_length=100, verbose_name='Danh mục')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store', verbose_name='Cửa hàng')),
            ],
        ),
    ]
