# Generated by Django 5.2.12 on 2026-03-22 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Tên danh mục')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã Icon FontAwesome')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('VENDOR', 'Người bán'), ('SHIPPER', 'Đơn vị vận chuyển'), ('ADMIN', 'Quản trị viên')], db_index=True, default='CUSTOMER', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('ai_personal_notes', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True)),
                ('intellishop_coin', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('full_address', models.TextField()),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_email', models.EmailField(db_index=True, max_length=100, verbose_name='Email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền ($)')),
                ('status', models.CharField(choices=[('PENDING', 'Cho vendor xac nhan'), ('READY_FOR_PICKUP', 'Cho shipper nhan don'), ('DELIVERING', 'Dang giao'), ('DELIVERED', 'Da giao'), ('FAILED', 'Giao that bai')], db_index=True, default='PENDING', max_length=32, verbose_name='Tình trạng')),
                ('payment_method', models.CharField(db_index=True, default='COD', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shop_voucher_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('intellishop_voucher_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coin_used', models.PositiveIntegerField(default=0)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày đặt')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả chi tiết')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Giá hiện tại ($)')),
                ('stock', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tồn kho')),
                ('status', models.CharField(choices=[('in_stock', 'Con hang'), ('out_of_stock', 'Het hang'), ('hidden', 'Bi an')], db_index=True, default='in_stock', max_length=20)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'Cho duyet'), ('ACTIVE', 'Da duyet'), ('REJECTED', 'Tu choi')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá cũ ($)')),
                ('is_hot', models.BooleanField(db_index=True, default=False, verbose_name='Là Deal Hot')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/%Y/%m/', verbose_name='Ảnh sản phẩm')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('variant', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShipperApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Tên công ty / Đơn vị')),
                ('vehicle_type', models.CharField(max_length=100, verbose_name='Loại phương tiện')),
                ('service_area', models.TextField(verbose_name='Khu vực phục vụ')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='shipper_applications/%Y/%m/', verbose_name='Giấy phép kinh doanh')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shipper_apps', to=settings.AUTH_USER_MODEL, verbose_name='Admin duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn đăng ký Đơn vị vận chuyển',
                'verbose_name_plural': 'Đơn đăng ký Đơn vị vận chuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Tên cửa hàng')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='store_icons/%Y/%m/', verbose_name='Logo thương hiệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('business_category', models.CharField(blank=True, max_length=100, verbose_name='Ngành hàng kinh doanh')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT doanh nghiệp')),
                ('store_address', models.TextField(blank=True, verbose_name='Địa chỉ cửa hàng')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tỉnh / Thành phố')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='business_licenses/%Y/%m/', verbose_name='Giấy phép kinh doanh')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='Chủ cửa hàng')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store', verbose_name='Cửa hàng'),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('ticket_type', models.CharField(choices=[('COMPLAINT', 'Khieu nai'), ('SUPPORT', 'Ho tro ky thuat')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Cho xu ly'), ('IN_PROGRESS', 'Dang xu ly'), ('RESOLVED', 'Da giai quyet')], db_index=True, default='PENDING', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Tên cửa hàng')),
                ('business_category', models.CharField(max_length=100, verbose_name='Ngành hàng kinh doanh')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT doanh nghiệp')),
                ('store_address', models.TextField(verbose_name='Địa chỉ cửa hàng')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Tỉnh / Thành phố')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả cửa hàng')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='vendor_applications/%Y/%m/', verbose_name='Giấy phép kinh doanh')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_apps', to=settings.AUTH_USER_MODEL, verbose_name='Admin duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn đăng ký Người bán',
                'verbose_name_plural': 'Đơn đăng ký Người bán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('register_activation', 'Kich hoat tai khoan'), ('reset_password', 'Dat lai mat khau')], db_index=True, max_length=32)),
                ('otp_code', models.CharField(max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='core_emailo_email_93959d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'user'), name='unique_store_review_per_user')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('percent', 'Phan tram'), ('fixed', 'So tien co dinh')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope', models.CharField(choices=[('store', 'Toan shop'), ('selected_products', 'San pham cu the')], default='store', max_length=30)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'code'), name='unique_voucher_code_per_store')],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_wishlist')],
            },
        ),
    ]
