# Generated by Django 5.2.12 on 2026-03-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_coin_used_order_insurance_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ngành hàng kinh doanh'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='Chủ cửa hàng'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ cửa hàng'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('VENDOR', 'Người bán'), ('SHIPPER', 'Đơn vị vận chuyển'), ('ADMIN', 'Quản trị viên')], db_index=True, default='CUSTOMER', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, default='Chờ duyệt', max_length=50, verbose_name='Tình trạng'),
        ),
        migrations.CreateModel(
            name='ShipperApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Tên công ty / Đơn vị')),
                ('vehicle_type', models.CharField(max_length=100, verbose_name='Loại phương tiện')),
                ('service_area', models.TextField(verbose_name='Khu vực phục vụ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shipper_apps', to=settings.AUTH_USER_MODEL, verbose_name='Admin duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn đăng ký Đơn vị vận chuyển',
                'verbose_name_plural': 'Đơn đăng ký Đơn vị vận chuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Tên cửa hàng')),
                ('business_category', models.CharField(max_length=100, verbose_name='Ngành hàng kinh doanh')),
                ('store_address', models.TextField(verbose_name='Địa chỉ cửa hàng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả cửa hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_apps', to=settings.AUTH_USER_MODEL, verbose_name='Admin duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn đăng ký Người bán',
                'verbose_name_plural': 'Đơn đăng ký Người bán',
                'ordering': ['-created_at'],
            },
        ),
    ]
