# Generated by Django 5.2.12 on 2026-03-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_is_hot_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=10, upload_to='', verbose_name='Hình ảnh (Emoji)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='icon',
            field=models.ImageField(max_length=10, upload_to='', verbose_name='Icon (Emoji)'),
        ),
    ]
