# Generated by Django 5.2.12 on 2026-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá hiện tại ($)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='store_icons/', verbose_name='Logo thương hiệu'),
        ),
    ]
