# Generated by Django 5.2.12 on 2026-03-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_emailot_email_c22843_idx_core_emailo_email_93959d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả chi tiết'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'Con hang'), ('out_of_stock', 'Het hang'), ('hidden', 'Bi an')], db_index=True, default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tồn kho'),
        ),
        migrations.AddField(
            model_name='store',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='business_licenses/%Y/%m/', verbose_name='Giấy phép kinh doanh'),
        ),
        migrations.AddField(
            model_name='store',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT doanh nghiệp'),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tỉnh / Thành phố'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='vendor_applications/%Y/%m/', verbose_name='Giấy phép kinh doanh'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT doanh nghiệp'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tỉnh / Thành phố'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('percent', 'Phan tram'), ('fixed', 'So tien co dinh')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope', models.CharField(choices=[('store', 'Toan shop'), ('selected_products', 'San pham cu the')], default='store', max_length=30)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'code'), name='unique_voucher_code_per_store')],
            },
        ),
    ]
