# Generated by Django 5.2.12 on 2026-03-20 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shipperprofile_and_order_status_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Cho duyet'), ('ACTIVE', 'Da duyet'), ('REJECTED', 'Tu choi')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('ticket_type', models.CharField(choices=[('COMPLAINT', 'Khieu nai'), ('SUPPORT', 'Ho tro ky thuat')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Cho xu ly'), ('IN_PROGRESS', 'Dang xu ly'), ('RESOLVED', 'Da giai quyet')], db_index=True, default='PENDING', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
